version: '3.3'

networks:
  codechat-net:
    driver: bridge

services:
  base:
    container_name: codechat_api
    image: codechat/api:latest
    ports:
      - 8084:8084
    volumes:
      - /data/instances:/codechat/instances
    command: ['node', './dist/src/main.js']

    networks:
      - codechat-net
